name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/p/widgetastic.patternfly5
    permissions:
      id-token: write  # For trusted publishing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install pip twine -U
      - name: Build a wheel
        run: pip wheel --no-deps -w dist .
      - name: Test package
        run: twine check dist/*
      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
